const countriesWithFlags = {
  // South Asia
  "India": "🇮🇳",
  "Bangladesh": "🇧🇩",
  "Nepal": "🇳🇵",
  "Sri Lanka": "🇱🇰",
  "Afghanistan": "🇦🇫",
  "Bhutan": "🇧🇹",
  "Maldives": "🇲🇻",

  // Middle East
  "United Arab Emirates": "🇦🇪",
  "Saudi Arabia": "🇸🇦",
  "Qatar": "🇶🇦",
  "Kuwait": "🇰🇼",
  "Bahrain": "🇧🇭",
  "Oman": "🇴🇲",
  "Jordan": "🇯🇴",
  "Lebanon": "🇱🇧",
  "Israel": "🇮🇱",
  "Turkey": "🇹🇷",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",

  // Europe
  "United Kingdom": "🇬🇧",
  "Germany": "🇩🇪",
  "France": "🇫🇷",
  "Italy": "🇮🇹",
  "Spain": "🇪🇸",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Switzerland": "🇨🇭",
  "Austria": "🇦🇹",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Denmark": "🇩🇰",
  "Finland": "🇫🇮",
  "Poland": "🇵🇱",
  "Russia": "🇷🇺",

  // North America
  "United States": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",

  // Asia Pacific
  "China": "🇨🇳",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Australia": "🇦🇺",
  "Singapore": "🇸🇬",
  "Thailand": "🇹🇭",
  "Malaysia": "🇲🇾",
  "Indonesia": "🇮🇩",
  "Vietnam": "🇻🇳",
  "Philippines": "🇵🇭",
  "New Zealand": "🇳🇿",

  // Africa
  "South Africa": "🇿🇦",
  "Nigeria": "🇳🇬",
  "Egypt": "🇪🇬",
  "Kenya": "🇰🇪",
  "Ghana": "🇬🇭",
  "Morocco": "🇲🇦",
  "Algeria": "🇩🇿",
  "Ethiopia": "🇪🇹",
  "Uganda": "🇺🇬",
  "Tanzania": "🇹🇿",

  // South America
  "Brazil": "🇧🇷",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Colombia": "🇨🇴",
  "Peru": "🇵🇪",
  "Venezuela": "🇻🇪",
  "Ecuador": "🇪🇨",

  // Countries without flags (excluded 15 countries)
  "Myanmar": null,
  "Cambodia": null,
  "Laos": null,
  "Mongolia": null,
  "Kazakhstan": null,
  "Uzbekistan": null,
  "Kyrgyzstan": null,
  "Tajikistan": null,
  "Turkmenistan": null,
  "Portugal": null,
  "Greece": null,
  "Czech Republic": null,
  "Hungary": null,
  "Romania": null,
  "Bulgaria": null,

  // Additional countries without flags
  "Croatia": null,
  "Serbia": null,
  "Ukraine": null,
  "Belarus": null,
  "Lithuania": null,
  "Latvia": null,
  "Estonia": null,
  "Moldova": null,
  "Slovenia": null,
  "Slovakia": null,
  "Bosnia and Herzegovina": null,
  "Montenegro": null,
  "North Macedonia": null,
  "Albania": null,
  "Kosovo": null,
  "Luxembourg": null,
  "Malta": null,
  "Iceland": null,
  "Ireland": null,
  "Cyprus": null,
  "Andorra": null,
  "Monaco": null,
  "Liechtenstein": null,
  "San Marino": null,
  "Vatican City": null
};

export default countriesWithFlags; 